# docker-compose 여러개의 컨테이너를 한번에 설정하고 실행(빌드)하게 도와주는 도구

version: '3.8'

services:
  app:
    build:
      context: .
    image:
    container_name:
    environment:
      SPRING_DATASOURCE_URL:
      SPRING_DATASOURCE_USERNAME:
      SPRING_DATASOURCE_PASSWORD:
    ports:
      - "8080:8080"
    networks:
      - gallery-net

volumes:
  db-data:

networks:
  gallery-net: